Language selection menu
emibcn/covid pull request #19
Opened 2020-10-08 17:46 UTC by Abhijith126

Please review this PR and let me know for any changes. 
I have modified the currently available languages object into an array and did the relevant changes needed to handle the language change.

2020-10-08 19:04 UTC, emibcn requested changes
I think it will be easier and cleare to add each language name into its own deffinition, and no need to translate them into the rest of languages. What do you think?

In the end (just before PR approval/merge), I'll make a PR against your forked repo to fix catalan ans spanish translations (my mother tongues), so they are ok before hitting `master`.

2020-10-08 19:04 UTC, emibcn commented on app/src/i18n/ca-es.lang.js
> +  fr: "Français",
No need to add each language name translated to all languages.

2020-10-09 12:31 UTC, Abhijith126 commented
Please check now, I have made the changes accordingly and tested them. Should be all good.

2020-10-09 13:07 UTC, emibcn commented
I've opened a PR against your fork to fix catalan and spanish translations. Merge it and then I'll merge the result here 👍🏾

2020-10-09 15:43 UTC, merged

2020-10-09 15:47 UTC, emibcn commented
[Thanked!](https://github.com/emibcn/covid#thanks-to)