Issue #17 - Add some lateral margin to Slider on non-small devices
emibcn/covid pull request #21
Opened 2020-10-09 02:13 UTC by mblaul

- Adding a small amount of left and right margin to the slider on large displays
- Removing style props from Slider component so class styles are not overridden

2020-10-09 10:16 UTC, emibcn requested changes
Looks almost great, just a couple of comments in the review.

2020-10-09 10:16 UTC, emibcn commented on app/src/Widget/List.jsx
> +      marginRight: theme.spacing(1),
I've tested with just `1` and it overlaps with lateral buttons. Looks like the minimal for small devices should be `3`.

2020-10-09 10:16 UTC, emibcn commented on app/src/Widget/List.jsx
> +    [theme.breakpoints.down('sm')]: {
To have all devices controlled, you should be using `down('md')` here

2020-10-09 21:04 UTC, mblaul commented
@emibcn Thanks for the review and comments. Sorry about that!
I have updated this PR to address those points.

2020-10-10 08:31 UTC, merged

2020-10-10 08:40 UTC, emibcn commented
[Thanked!](https://github.com/emibcn/covid#thanks-to)