Fix #12
emibcn/covid pull request #27
Opened 2020-10-10 13:24 UTC by ashish979

reference: https://chanind.github.io/javascript/2019/09/28/avoid-100vh-on-mobile-web.html

2020-10-10 17:28 UTC, emibcn commented
It does not looks very good, sorry:
- `style` is not applied to MaterialUI components. It uses `useStyle` or `makeStyles`: https://material-ui.com/styles/basics/#adapting-based-on-props
- If it worked, it'd have been applied to all devices (making full height dialog also for large screens, too)

My mobile works well with the current production version, so this needs a hack only for buggy devices.
I suppose the hack has to be applied:
- Only when the `fullscreen` variable is `true`
- Each time the dialog is opened. It means, recalculate and reapply the style each time it opens. For this, it should use a special form of `makeStyle` [based on props](https://material-ui.com/styles/basics/#adapting-based-on-props)
- Only when an `100hv` element's height is higher than `window.innerHeight` (maybe this condition is not necessary)

Does it makes sense or am I missing something?

2020-10-10 17:28 UTC, emibcn requested changes
It does not looks very good, sorry:
- `style` is not applied to MaterialUI components. It uses `useStyle` or `makeStyles`: https://material-ui.com/styles/basics/#adapting-based-on-props
- If it worked, it'd have been applied to all devices (making full height dialog also for large screens, too)

My mobile works well with the current production version, so this needs a hack only for buggy devices.
I suppose the hack has to be applied:
- Only when the `fullscreen` variable is `true`
- Each time the dialog is opened. It means, recalculate and reapply the style each time it opens. For this, it should use a special form of `makeStyle` [based on props](https://material-ui.com/styles/basics/#adapting-based-on-props)
- Only when an `100hv` element's height is higher than `window.innerHeight` (maybe this condition is not necessary)

Does it makes sense or am I missing something?

2020-10-10 17:39 UTC, emibcn commented
Investigating more, I've found:
- The buggy one is not the device, but the browser: Firefox based ones got this error
- Tried with that the version proposed in this PR and, effectively, it's not solving the problem
- Maybe it can be easily solved using `paperFullScreen` property from [Material UI Dialog](https://material-ui.com/api/dialog/#css)

2020-10-12 05:48 UTC, ashish979 commented
> Investigating more, I've found:
> 
> * The buggy one is not the device, but the browser: Firefox based ones got this error
> * Tried with that the version proposed in this PR and, effectively, it's not solving the problem
> * Maybe it can be easily solved using `paperFullScreen` property from [Material UI Dialog](https://material-ui.com/api/dialog/#css)

2020-10-12 05:48 UTC, closed without merging